### ISSUE TITLE
Please publish new version with current module name

### ISSUE THREAD

**Issue by aelse** [denis-tingaikin/go-header#21]
Hi @denis-tingaikin. Go get fails for go 1.17.

```
$ go get github.com/denis-tingaikin/go-header
go get: github.com/denis-tingaikin/go-header@v0.4.2: parsing go.mod:
        module declares its path as: github.com/denis-tingajkin/go-header
                but was required as: github.com/denis-tingaikin/go-header
```

You can get around this by running `go get github.com/denis-tingaikin/go-header@HEAD` but it would be better to publish a new version so this works as expected for published versions.

This is important as a step to updating dependencies in other projects since the old repo location no longer exists and is vulnerable to account takeover where a malicious user can then publish bad code.

**Comment by denis-tingaikin** [comment]
Should be done in https://github.com/denis-tingaikin/go-header/releases/tag/v0.4.3

**Comment by aelse** [comment]
Thanks @denis-tingaikin

**Comment by denis-tingaikin** [comment]
Seems like resolved. Closing this one. Be free to reopen if I missed something.
